export const NAV_MAIN_SCREEN = 'NAV_MAIN_SCREEN'
export const NAV_CCCY_SCREEN = 'NAV_CCCY_SCREEN'
export const NAV_FX_SCREEN = 'NAV_FX_SCREEN'
export const NAV_EQUITIES_SCREEN = 'NAV_EQUITIES_SCREEN'

export const QUOTE_SEARCH_START = 'QUOTE_SEARCH_START'
export const QUOTE_SEARCH_FOUND = 'QUOTE_SEARCH_FOUND'
export const QUOTE_SEARCH_ERROR = 'QUOTE_SEARCH_ERROR'
